const copies = {
  CONTINUE: 'Continue',
  SIGN_UP: 'Sign Up',
  BY_CONTINUING_YOU_AGREE_TO_OUT: 'By continuing, you agree to our',
  TERMS_AND_SERVICES: 'Terms and Services',
  PRIVACY_POLICY: 'Privacy Policy',
  CART: 'Cart',
  SEARCH: 'Search',
  MINS: 'mins',
  LOGIN: 'Login',
  YOUR_PROFILE: 'Your Profile',
  YOUR_ORDERS: 'Your Orders',
  ABOUT: 'About',
  SIGN_OUT: 'Sign Out',
  ORDER_PLACED_ON: 'Order placed on',
  RUPEE: '\u20B9',
  RATINGS: 'ratings',
  MY_CARTS: 'My Carts',
  ORDER_TOTAL: 'Order Total',
  YOUR_CART_IS_EMPTY: 'Your Cart is Empty!',
  ORDER: 'Order',
  ORDER_SUMMARY: 'Order Summary',
  YOUR_ITEMS: 'Your Items',
  ITEM_TOTAL: 'Item Total',
  TAXES: 'Taxes',
  DELIVERY_CHARGE: 'Delivery Charge',
  PLATFORM_FEE: 'Platform Fee',
  GRAND_TOTAL: 'Grand Total',
  PLACE_ORDER: 'Place Order',
  ENTER_OTP: 'Enter OTP',
  YOU_HAVE_SUCCESSFULLY_PLACED_YOUR_ORDER:
    'You have successfully placed your order !',
  TRACK_ORDER: 'Track Order',
  SORRY_YOUR_ORDER_HAS_FAILED_PLEASE_TRY_AGAIN_LATER:
    'Sorry! Your Order has failed. Please, Try again later !',
  ORDER_FAST: 'Order Fast',
  ORDER_YOUR_FOOD: 'Order your Food',
  A_GOOD_MEAL_CAN_TURN_ANY_DAY_AROUND_ORDER_NOW_FOR_DELICIOUS_CRAVINGS:
    'A good meal can turn any day around.\nOrder now for delicious cravings.',
  NEXT: 'Next',
  EASY_PAYMENT: 'Easy Payment',
  SAFE_ONLINE_PAYMENT: 'Safe Online Payment',
  AS_PART_OF_SECURE_PAYMENT:
    'As part of a secure payment, your credit/\nDabit card number, expiry are encrypted',
  FAST_DELIVERY: 'Fast Delivery',
  DELIVERY_AT_YOUT_DOORSTEP: 'Delivery at your Doorstep',
  WE_PROVIDE_DOOR_TO_DOOR_SERVICE:
    'We provide door to door service in\nmean time with best quality of food',
  PHONE_NO: 'Phone No.',
  PHILIPPINES_COUNTRY_CODE: '+63',
  EXAMPLE_PH_NO: 'Ex: 9070000000',
  SIGN_IN: 'Sign In',
  OR: 'Or',
  CONTENT_POLICIES: 'Content Policies',
  SIGN_IN_WITH_EMAIL: 'Sign in with email',
  DELIVER_TO: 'Deliver to',
  SPECIAL_OFFERS: 'Special Offers',
  CATEGORIES: 'Categories',
  SEE_ALL: 'See All',
  FEATURED_MERCHANTS: 'Featured Merchants',
  DOT: '\u2022',
  RESTAURANTS_NEAR_YOU: 'Restaurants near You',
  NEW_ON_HERO_MEALS: 'New on HeroMeals',
  COLLECT_NOW: 'Collect Now',
  LIST: 'List',
  MAP: 'Map',
  OPENING_HOURS: 'Opening Hours:',
  TODAY: 'Today',
  SOLD_OUT: 'Sold out',
  LEFT: 'left',
  PESO: '\u20B1',
  MENU_ITEMS: 'Menu Items',
  FRIENDLY_STAFF: 'Friendly Staff',
  DELICIOUS_FOOD: 'Delicious Food',
  GREAT_AMOUNT_OF_FOOD: 'Great amount of food',
  REVIEWS: 'Reviews',
  ABOUT_STORE: 'About store',
  BASED_ON_72_RATINGS_OVER_THE_PAST_MONTH:
    'Based on 72 ratings over the past month',
  CHECKOUT: 'Checkout',
  DELIVERY: 'Delivery',
  PICKUP: 'Pickup',
  SHIP_TO: 'Ship to',
  PICKUP_AT: 'Pickup at',
  CHANGE: 'Change',
  VIEW_MAP: 'View map',
  DELIVERY_EXPECTED_BETWEEN: 'Delivery expected between',
  PICKUP_TODAY_FROM: 'Pickup Today from',
  TO: 'to',
  NOTIFY_ME: 'Notify Me',
  MY_BASKET: 'My Basket',
  ADD_ITEMS: 'Add items',
  BACK: 'Back',
  EMPTY_BASKET: 'Empty Basket!',
  PAYMENT: 'Payment',
  DELIVERY_FEE: 'Delivery Fee',
  PICKUP_DISCOUNT: 'Pickup Discount',
  TO_PAY: 'To Pay',
  PAYMENT_METHOD: 'Payment Method ',
  CASH_ON_DELIVERY: 'Cash on Delivery',
  VISA: 'Visa',
  MASTERCARD: 'Mastercard',
  GCASH: 'GCash',
};

export default copies;
