const copies = {
  FDA: 'FDA',
  NUMBER_1_FOOD_DELIVERY_APP_IN_INDIA: '#1 food delivery app in india',
  NUMBER_1_FOOD_DELIVERY_APP_IN_INDIA_CAPITALIZED:
    '#1 Food Delivery App In India',
  ENTER_MOBILE_NUMBER: 'Enter Mobile Number',
  CONTINUE: 'Continue',
  LOGIN_OR: 'Login or',
  SIGN_UP: 'sign up',
  BY_CONTINUING_YOU_AGREE_TO_OUT: 'By continuing, you agree to our',
  TERMS_AND_SERVICES: 'Terms and Services',
  PRIVACY_POLICY: 'Privacy Policy',
  CART: 'Cart',
  SEARCH: 'Search',
  INDIA_COUNTRY_CODE: '+91',
  MINS: 'mins',
  LOGIN: 'Login',
  RESEND_OTP: 'Resend OTP',
  BACK: 'Back',
  YOUR_PROFILE: 'Your Profile',
  YOUR_ORDERS: 'Your Orders',
  ABOUT: 'About',
  SIGN_OUT: 'Sign Out',
  ORDER_PLACED_ON: 'Order placed on',
  RUPEE: '\u20B9',
  RATINGS: 'ratings',
  MY_CARTS: 'My Carts',
  ORDER_TOTAL: 'Order Total',
  YOUR_CART_IS_EMPTY: 'Your Cart is Empty!',
  ORDER: 'Order',
  ORDER_SUMMARY: 'Order Summary',
  YOUR_ITEMS: 'Your Items',
  ITEM_TOTAL: 'Item Total',
  TAXES: 'Taxes',
  DELIVERY_CHARGE: 'Delivery Charge',
  PLATFORM_FEE: 'Platform Fee',
  GRAND_TOTAL: 'Grand Total',
  PLACE_ORDER: 'Place Order',
  ENTER_OTP: 'Enter OTP',
};

export default copies;
