const copies = {
  NUMBER_1_FOOD_DELIVERY_APP_IN_INDIA_CAPITALIZED:
    '#1 Food Delivery App In India',
  ENTER_MOBILE_NUMBER: 'Enter Mobile Number',
  CONTINUE: 'Continue',
  LOGIN_OR: 'Login or',
  SIGN_UP: 'sign up',
  BY_CONTINUING_YOU_AGREE_TO_OUT: 'By continuing, you agree to our',
  TERMS_AND_SERVICES: 'Terms and Services',
  PRIVACY_POLICY: 'Privacy Policy',
  CART: 'Cart',
  SEARCH: 'Search',
  INDIA_COUNTRY_CODE: '+91',
  MINS: 'mins',
  LOGIN: 'Login',
  RESEND_OTP: 'Resend OTP',
  BACK: 'Back',
  YOUR_PROFILE: 'Your Profile',
  YOUR_ORDERS: 'Your Orders',
  ABOUT: 'About',
  SIGN_OUT: 'Sign Out',
  ORDER_PLACED_ON: 'Order placed on',
  RUPEE: '\u20B9',
  RATINGS: 'ratings',
  MY_CARTS: 'My Carts',
  ORDER_TOTAL: 'Order Total',
  YOUR_CART_IS_EMPTY: 'Your Cart is Empty!',
  ORDER: 'Order',
  ORDER_SUMMARY: 'Order Summary',
  YOUR_ITEMS: 'Your Items',
  ITEM_TOTAL: 'Item Total',
  TAXES: 'Taxes',
  DELIVERY_CHARGE: 'Delivery Charge',
  PLATFORM_FEE: 'Platform Fee',
  GRAND_TOTAL: 'Grand Total',
  PLACE_ORDER: 'Place Order',
  ENTER_OTP: 'Enter OTP',
  YOU_HAVE_SUCCESSFULLY_PLACED_YOUR_ORDER:
    'You have successfully placed your order !',
  TRACK_ORDER: 'Track Order',
  SORRY_YOUR_ORDER_HAS_FAILED_PLEASE_TRY_AGAIN_LATER:
    'Sorry! Your Order has failed. Please, Try again later !',
  ORDER_FAST: 'Order Fast',
  ORDER_YOUR_FOOD: 'Order your Food',
  A_GOOD_MEAL_CAN_TURN_ANY_DAY_AROUND_ORDER_NOW_FOR_DELICIOUS_CRAVINGS:
    'A good meal can turn any day around.\nOrder now for delicious cravings.',
  NEXT: 'Next',
  EASY_PAYMENT: 'Easy Payment',
  SAFE_ONLINE_PAYMENT: 'Safe Online Payment',
  AS_PART_OF_SECURE_PAYMENT:
    'As part of a secure payment, your credit/\nDabit card number, expiry are encrypted',
  FAST_DELIVERY: 'Fast Delivery',
  DELIVERY_AT_YOUT_DOORSTEP: 'Delivery at your Doorstep',
  WE_PROVIDE_DOOR_TO_DOOR_SERVICE:
    'We provide door to door service in\nmean time with best quality of food',
};

export default copies;
